import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Logger;

/**
 * @author manfred
 */
public class GroupExcel extends JFrame {

    private JButton importExcelButton;
    private JLabel jLabelImage;
    private JScrollPane jScrollPane1;

    private JTextArea result;

    /**
     * Creates new form AddDataToJTable
     */
    public GroupExcel() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
        result = new JTextArea(100, 100);
        jScrollPane1 = new JScrollPane();
        jLabelImage = new JLabel();
        importExcelButton = new JButton();
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        jScrollPane1.setViewportView(result);
        importExcelButton.setText("Import (Excel)");
        importExcelButton.addActionListener(this::importExcelActionPerformed);
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                                .addComponent(jLabelImage, GroupLayout.PREFERRED_SIZE, 146, GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(importExcelButton, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelImage, GroupLayout.PREFERRED_SIZE, 121, GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(importExcelButton, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(5, 5, 5)))))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 251, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(31, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(null);
    }

    private void importExcelActionPerformed(java.awt.event.ActionEvent evt) {
        result.setText("");
        File excelFile;
        XSSFWorkbook importExcelWorkBook;
        FileSystemView fsv = FileSystemView.getFileSystemView();
        JFileChooser excelFileChooser = new JFileChooser(fsv.getHomeDirectory());
        excelFileChooser.setDialogTitle("Select Excel File");
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXCEL FILES", "xls", "xlsx", "xlsm");
        excelFileChooser.setFileFilter(fnef);
        int excelChooser = excelFileChooser.showOpenDialog(null);
        if (excelChooser == JFileChooser.APPROVE_OPTION) {
            excelFile = excelFileChooser.getSelectedFile();
            try (FileInputStream excelFis = new FileInputStream(excelFile);
                 BufferedInputStream excelBis = new BufferedInputStream(excelFis);) {
                importExcelWorkBook = new XSSFWorkbook(excelBis);
                for (XSSFSheet excelSheet : importExcelWorkBook) {
                    XSSFCell xssfCell = excelSheet.getRow(0).getCell(0);
                    if (null != xssfCell
                            && null != xssfCell.getRawValue()
                            && Cell.CELL_TYPE_STRING == xssfCell.getCellType()
                            && xssfCell.getStringCellValue().contains("CUC")) {
                        int dataBeganRow = 1;
                        for (int row = 1; row < excelSheet.getLastRowNum(); row++) {
                            XSSFRow excelRow = excelSheet.getRow(row);
                            xssfCell = excelRow.getCell(6);
                            if (null != xssfCell
                                    && null != xssfCell.getRawValue()
                                    && Cell.CELL_TYPE_STRING == xssfCell.getCellType()
                                    && xssfCell.getStringCellValue().contains("科目组合")) {
                                dataBeganRow = row + 1;
                                break;
                            }
                        }
                        Map<String, Double> sheetGroupResult = new HashMap<>();
                        for (int row = dataBeganRow; row < excelSheet.getLastRowNum(); row++) {
                            XSSFRow excelRow = excelSheet.getRow(row);
                            String[] strings = excelRow.getCell(6).getStringCellValue().split("\\.");
                            sheetGroupResult.putIfAbsent(strings[3], 0.0);
                            sheetGroupResult.put(strings[3], sheetGroupResult.get(strings[3]) + excelRow.getCell(7).getNumericCellValue());
                        }
                        StringBuilder strResult = new StringBuilder();
                        DecimalFormat format = new DecimalFormat("#0.00");
                        sheetGroupResult.forEach((k, v) -> {
                            strResult.append("\t").append(k).append(": ").append(format.format(v)).append("\n");
                        });
                        result.insert("sheet- <" + excelSheet.getSheetName() + ">\n" + strResult + "\n\n", 0);
                    } else {
                        result.append("sheet- <" + excelSheet.getSheetName() + "> 格式不符合\n");
                    }
                }

            } catch (IOException ioException) {
                JOptionPane.showMessageDialog(null, ioException.getMessage());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(GroupExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new GroupExcel().setVisible(true));
    }
}