是指权利人依法对特定的物享有 *直接支配* 和 *排他* 的权利，包括所有权和他物权（用益物权和担保物权）。或者说，指自然人、法人直接支配不动产或者动产的权利，包括所有权、用益物权和担保物权。不动产指土地以及建筑物等土地附着物；动产指不动产以外的物。制定物权法，对明确物的归属，充分发挥物的效用，维护经济秩序，促进社会主义现代化建设，具有更加重要意义

他物权是在他人所有的物上设定或享有的权利。源于罗马法。按罗马法理论，自物权即所有权以外的一切物权均可纳入他物权范畴。此类权利以他人的所有权为前提而存在，通常仅体现为物权的某项权能或某一部份，实质上是对所有权的限制。罗马法上的他物权一般包括役权、永佃权、地上权和质权四种。近现代民法承袭了罗马法的他物权概念及理论，但在其具体表现形式上则有越来越丰富的发展。学理上往往将他物权称为“不完全物权”或“限制物权”，并将其具体划分为用益物权和担保物权两类。

用益物权，是指以一定范围内的使用、收益为目的而在他人之物上设立的定限物权。比如土地承包经营权、建设用地使用权、宅基地使用权、地役权、居住权、自然资源使用权（海域使用权、探矿权、采矿权、取水权和使用水域、滩涂从事养殖、捕捞的权利）。

担保物权，“用益物权”的对称。是指他物权或限制物权的一类。为了担保债权的实现，由债务人或第三人提供特定的物或者权利作为标的物而设定的限定物权。如抵押权、质权、留置权等。担保物权不以标的物的实体利用为目的，而是注重于其交换价值，以确保债务的履行，故又被称为“价值权”，其标的物必须具有交换价值。至于权利客体价值形态的变化，并不影响担保物权的存在。因而担保物权具有物上代位性，即当担保物权的标的物转化为其他价值形态时，担保物权以变形物为客体。担保物权以债权的存在为前提，具有附随性。


== 参考
[%hardbreaks]
https://baike.baidu.com/item/%E7%89%A9%E6%9D%83[物权 @百度百科]
https://baike.baidu.com/item/%E4%BB%96%E7%89%A9%E6%9D%83[他物权 @百度百科]
https://baike.baidu.com/item/%E7%94%A8%E7%9B%8A%E7%89%A9%E6%9D%83[用益物权 @百度百科]
https://baike.baidu.com/item/%E6%8B%85%E4%BF%9D%E7%89%A9%E6%9D%83[担保物权 @百度百科]