== 一、方法调用

方法调用不同于方法执行，方法调用阶段的唯一任务就是确定被调用方法的版本（即调用哪一个方法）， 暂时还不涉及方法内部的具体运行过程。Class文件的编译过程中不包括传统编译器中的连接步骤，一切方法调用在Class 文件里面存储的都是符号引用，而不是方法在实际运行时内存布局中的入口地址（直接引用）。 也就是需要在类加载阶段，甚至到运行期才能确定目标方法的直接引用。

== 二、解析

如前所述，所有的方法调用中的目标方法在Class文件里面都是一个常量池中的符号引用，在类加载阶段，会将其中的一部分符号引用转化为直接引用，这种解析能成立的前提是：方法在程序真正运行之前就有一个可确定的调用版本，并且这个方法的调用版本在运行期间是不可变的。也就是说，调用目标在程序代码写好、编译器进行编译时就必须确定下来，这类方法的调用成为解析。 +
JAVA中符号“编译器可知、运行期不可变”的方法包括：静态方法、私有方法两大类。前者与类型直接关联，后者在外部不可被访问，这就决定了他们都不可能通过继承或别的方式重写其版本。因此都适合在类的加载阶段进行解析。 +
JAVA虚拟机里面提供了5条方法调用字节码指令。分别如下：

* invokestatic:调用静态方法
* invokespecial:调用实例构造器<init>方法、私有方法和父类方法（super(),super.method()）。
* invokevirtual:调用所有的虚方法(静态方法、私有方法、实例构造器、父类方法、final方法都是非虚方法)。
* invokeinterface:调用接口方法，会在运行时期再确定一个实现此接口的对象。
* invokedynamic:现在运行时期动态解析出调用点限定符所引用的方法，然后再执行该方法，在此之前的4条指令，分派逻辑都是固化在虚拟机里面的，而invokedynamic指令的分派逻辑是由用户所设定的引导方法决定的。

只要能被invokestatic和invokespecial指令调用的方法都可以在解析阶段中确定唯一的调用版本，符合这个条件的有静态方法、私有方法、实例构造器、父类方法4类，它们在类加载阶段就会把符号引用解析为该方法的直接引用。这些方法称为非虚方法（还包括使用final修饰的方法，虽然final方法使用invokevirtual指令调用，因为final方法注定不会被重写，也就是无法被覆盖，也就无需对其进行多态选择）。

== 参考

[%hardbreaks]
https://zhuanlan.zhihu.com/p/96777345[Java方法调用原理]
https://www.cnblogs.com/chenyangyao/p/5305352.html[图解JVM执行引擎之方法调用]
