____
软件工程师并没有创造新的东西，只不过是数字世界的砖瓦工，计算机系统中合乎逻辑的过程，停电后人肉使用纸和笔一样合乎逻辑。
____


[format="csv", options="header"]
|===
名词,释义,备注
模型,模型是指对于某个实际问题或客观事物、规律进行抽象后的一种形式化表达方式。,
领域,边界 + 业务逻辑,领域，指的特定行业或者场景下的业务逻辑。
领域模型,是指反映 IT 系统的业务逻辑和状态的对象，是从具体业务（领域）中提取出来的，因此又叫做领域模型。,
限界上下文,,
领域驱动设计,通过对实际业务出发，而非马上关注数据库、程序设计。通过识别出固定的模式，并将这些业务逻辑的承载者抽象到一个模型上。这个模型负责处理业务逻辑，并表达当前的系统状态。这个过程就是领域驱动设计。,
|===



== 设计领域模型的一般步骤如下
* 根据需求划分出初步的领域和限界上下文，以及上下文之间的关系；
* 进一步分析每个上下文内部，识别出哪些是实体，哪些是值对象；
* 对实体、值对象进行关联和聚合，划分出聚合的范畴和聚合根；
* 为聚合根设计仓储，并思考实体或值对象的创建方式；
* 在工程中实践领域模型，并在实践中检验模型的合理性，倒推模型中不足的地方并重构。

== 定义
*战略建模* +

. *领域*：*边界* + *业务逻辑（设计）* +

. *限界上下文*：*用户* + *领域模型* + *功能* +
  一个由显示边界限定的特定职责。领域模型便存在于这个边界之内。
  在边界内，每一个模型概念，包括它的属性和操作，都具有特殊的含义。
[quote]
[%hardbreaks]
康威（梅尔·康威）定律
任何组织在设计一套系统（广义概念上的系统）时，所交付的设计方案在结构上都与该组织的沟通结构保持一致。

. 上下文映射图：上下文间的关系
[quote]
[%hardbreaks]
*限界上下文之间的映射关系*
 合作关系（Partnership）：两个上下文紧密合作的关系，一荣俱荣，一损俱损。
 共享内核（Shared Kernel）：两个上下文依赖部分共享的模型。
 客户方-供应方开发（Customer-Supplier Development）：上下文之间有组织的上下游（上游：供应方 | 下游：客户方）依赖。
 遵奉者（Conformist）：下游上下文只能盲目依赖上游上下文。
 防腐层（AntiCorruption Layer）：一个上下文通过一些适配和转换与另一个上下文交互。
 开放主机服务（Open Host Service）：定义一种协议来让其他上下文来对本上下文进行访问。
 发布语言（Published Language）：通常与OHS一起使用，用于定义开放主机的协议。
 大泥球（Big Ball of Mud）：混杂在一起的上下文关系，边界不清晰。
 另谋他路（SeparateWay）：两个完全没有任何联系的上下文。

*战术建模* +

. 实体: 当一个对象由其标识（而不是属性）区分时，这种对象称为实体（Entity）。
  例：最简单的，公安系统的身份信息录入，对于人的模拟，即认为是实体，因为每个人是独一无二的，
  且其具有唯一标识（如公安系统分发的身份证号码）。
. 值对象: 当一个对象用于对事务进行描述而没有唯一标识时，它被称作值对象（Value Object）。
  例：比如颜色信息，我们只需要知道{“name”:“黑色”，”css”:“#000000”}这样的值信息就能够满足要求了，
  这避免了我们对标识追踪带来的系统复杂性。
. 聚合根: Aggregate(聚合）是一组相关对象的集合，作为一个整体被外界访问，
  聚合根（Aggregate Root）是这个聚合的根节点。
. 领域服务: 一些重要的领域行为或操作，可以归类为领域服务。它既不是实体，也不是值对象的范畴。
. 领域事件: 领域事件是对领域内发生的活动进行的建模。

== 实践
. 如何创建好的聚合？
* 边界内的内容具有一致性：在一个事务中只修改一个聚合实例。如果你发现边界内很难接受强一致，
  不管是出于性能或产品需求的考虑，应该考虑剥离出独立的聚合，采用最终一致的方式。
* 设计小聚合：大部分的聚合都可以只包含根实体，而无需包含其他实体。即使一定要包含，
  可以考虑将其创建为值对象。
* 通过唯一标识来引用其他聚合或实体：当存在对象之间的关联时，建议引用其唯一标识而非引用其整体对象。
  如果是外部上下文中的实体，引用其唯一标识或将需要的属性构造值对象。 如果聚合创建复杂，
  推荐使用工厂方法来屏蔽内部复杂的创建逻辑。
* 聚合内部多个组成对象的关系可以用来指导数据库创建，但不可避免存在一定的抗阻。如聚合中存在List<值对象>，
  那么在数据库中建立1:N的关联需要将值对象单独建表，此时是有id的，建议不要将该id暴露到资源库外部，对外隐蔽。

. 如何使用防腐层
* 亦称适配层。在一个上下文中，有时需要对外部上下文进行访问，通常会引入防腐层的概念来对外部上下文的访问进行一次转义。
* 有以下几种情况会考虑引入防腐层：
** 需要将外部上下文中的模型翻译成本上下文理解的模型。
** 不同上下文之间的团队协作关系，如果是供奉者关系，建议引入防腐层，避免外部上下文变化对本上下文的侵蚀。
** 该访问本上下文使用广泛，为了避免改动影响范围过大。

== 参考
[%hardbreaks]
https://tech.meituan.com/2017/12/22/ddd-in-practice.html[领域驱动设计在互联网业务开发中的实践]
https://insights.thoughtworks.cn/ddd-business-design/[使用DDD指导业务设计的一点思考 @ thoughtworks]
https://zhuanlan.zhihu.com/p/340911587[阿里技术专家详解 DDD 系列 第一讲- Domain Primitive]
https://zhuanlan.zhihu.com/p/343388831[阿里技术专家详解DDD系列 第二讲 - 应用架构]
https://zhuanlan.zhihu.com/p/348706530[阿里技术专家详解DDD系列 第三讲 - Repository模式]
https://zhuanlan.zhihu.com/p/356518017[阿里技术专家详解DDD系列 第四讲 - 领域层设计规范]
https://zhuanlan.zhihu.com/p/366395817[阿里技术专家详解DDD系列 第五讲：聊聊如何避免写流水账代码]

